Distro: "ubuntu18.04"
Graphene:
    Repository: "https://github.com/oscarlab/graphene.git"
    Branch: "2e737e69f076c60918f87d6829bb769925e75fec"
SGXDriver:
    Repository: # in-kernel driver needs no repository
    Branch: 
